definer('i18n.wx.yci.yexp.exp0501.approveview', {
    'zh_CN': {
    	basicInfoTitle: "基本信息",
    	applyDate: "申请日",
    	projectCd: "项目代码",
    	projectName: "项目名",
    	pmName: "项目负责人",
    	ReimbursePurpose:"目的",
    	companyName: "公司名称",
    	matterId:"案件号",
    	payDate:"支付日",
    	shuoming:"说明",
    	hasEexpenseFlag:"有其他经费报销",
    	buName: "事业部",
    	deptName: "部门",
    	costCenterName: "成本中心",
    	amount:"金额",
    	payWayName:"支付方式",
    	purpose:"用途",
    	Total:"其他经费报销合计",
    	writeOffAmount:"借款冲销金额",
        paymentAmount:"报销支付金额",
    	companyAmount:"公司信用卡",
    	detailTotal:"报销申请<br />总金额",
    	
    	accountingInfo1: "财务支付（记账日／希望支付日／凭证抬头文本）",
    	accountingInfo2: "财务支付（记账日／凭证抬头文本）",
    	accountingDebtorFlagName: "借贷区分",
    	accountingExpBroadCategoryName: "经费大分类",
    	accountingExpSubCategoryName: "经费小分类",
    	accountingExpItemName: "经费项目",
    	accountingSubjectName: "科目",
    	accountingPaymentAmountTaxIn: "含税金额",
    	accountingTaxRate: "税率",
    	accountingPaymentAmountTaxOut: "费用金额",
    	accountingTaxAmount: "税额",
    	accountingCurrencyName: "币种",
    	accountingExchangeRate: "汇率",
    	accountingCostCenterCd: "成本中心",
    	accountingInvoice: "发票",
    	accountingPartner: "合作伙伴",
    	accountingSummary: "行文本摘要",
    	payment:"合计(个人支付／公司信用卡)",
    	TotalTax:"含税金额合计",
    	TotalCost:"费用金额合计",
    	Totaltaxamount:"税额合计",
    },
    'ja': {
    	basicInfoTitle: "基本情報",
    	applyDate: "申請日",
    	projectCd: "プロジェクトコード",
    	projectName: "プロジェクト名称",
    	pmName: "プロジェクト責任者",
    	ReimbursePurpose:"目的",
    	companyName: "会社名称",
    	matterId:"案件番号",
    	payDate:"支払日",
    	shuoming:"説明",
    	hasEexpenseFlag:"その他経費精算あり",
    	buName: "事業部",
    	deptName: "部門",
    	costCenterName: "コストセンター",
    	amount:"金額",
    	payWayName:"支払方式",
    	purpose:"用途",
    	Total:"その他経費精算合計",
    	writeOffAmount:"仮払金相殺金額",
        paymentAmount:"精算支払金額",
    	companyAmount:"会社クレジットカード",
    	detailTotal:"総合計",
    	
    	accountingInfo1: "財務支払（転記日／希望支払日／仕訳概要テキスト）",
    	accountingInfo2: "財務支払（転記日／仕訳概要テキスト）",
    	accountingDebtorFlagName: "借貸区分",
    	accountingExpBroadCategoryName: "経費大分類",
    	accountingExpSubCategoryName: "経費小分類",
    	accountingExpItemName: "経費項目",
    	accountingSubjectName: "勘定科目",
    	accountingPaymentAmountTaxIn: "税込金額",
    	accountingTaxRate: "税率",
    	accountingPaymentAmountTaxOut: "費用金額<br />(CNY)",
    	accountingTaxAmount: "税額",
    	accountingCurrencyName: "通貨",
    	accountingExchangeRate: "為替レート",
    	accountingCostCenterCd: "コストセンター",
    	accountingInvoice: "発票",
    	accountingPartner: "パートナー",
    	accountingSummary: "仕訳明細テキスト",
    	payment:"合計(個人支払／コーポレートカード)",
    	TotalTax:"税込金額合計",
    	TotalCost:"費用金額合計",
    	Totaltaxamount:"税額合計",
    },
    'en': {
    	basicInfoTitle: "Basic Information",
    	applyDate: "Apply Date",
    	projectCd: "PJ Cd",
    	projectName: "PJ Name",
    	pmName: "PM",
    	ReimbursePurpose:"Purpose",
    	companyName: "Company Name",
    	matterId:"Application No.",
    	payDate:"Pay Date",
    	shuoming:"Description",
    	hasEexpenseFlag:"Has Other Expense Settlement",
    	buName: "Business Department",
    	deptName: "Department",
    	costCenterName: "Cost Centre",
    	amount:"Amount",
    	payWayName:"Payment Way",
    	purpose:"Uses",
    	Total:"Total Other Expense",
    	writeOffAmount:"Advance Payment Offset",
        paymentAmount:"Payment Amount",
    	companyAmount:"Company Credit Card",
    	detailTotal:"Settlement Total Amount",
    	
    	accountingInfo1: "Payment（Posting Date／Hope to pay day／Journal Outline Text）",
    	accountingInfo2: "Payment（Posting Date／Journal Outline Text）",
    	accountingDebtorFlagName: "Debit/Credit",
    	accountingExpBroadCategoryName: "Large Expense Type",
    	accountingExpSubCategoryName: "Small Expense Type",
    	accountingExpItemName: "Expense Items",
    	accountingSubjectName: "Accounting Items",
    	accountingPaymentAmountTaxIn: "Including Tax Amount",
    	accountingTaxRate: "Tax Rate",
    	accountingPaymentAmountTaxOut: "Excluding Tax Amount(CNY)",
    	accountingTaxAmount: "Tax Amount",
    	accountingCurrencyName: "Currency",
    	accountingExchangeRate: "Exchange Rate",
    	accountingCostCenterCd: "Cost Centre",
    	accountingInvoice: "Invoice",
    	accountingPartner: "Partner",
    	accountingSummary: "Journal Detail Text",
    	payment:"Total Amount(Personal payment／Company Credit Card)",
    	TotalTax:"Total Including Tax Amount",
    	TotalCost:"Total Expense Amount",
    	Totaltaxamount:"Total Tax Amount",
    }
});
