definer('i18n.wx.ysw.yexp.exp1201.approveview', {
    'zh_CN': {
    	expSubCategategory:"经费大分类",
    	expSubCategory:"经费小分类",
    	commonMsg:"基本信息",
    	applyDate:"申请日",
    	hopePayDate:"希望支付日",
    	companyCd:"公司名称",
    	instruction:"说明",
    	payAmount:"金额",
    	payMethod:"支付方式",
    	accountingInfo1: "财务支付（记账日／希望支付日／凭证抬头文本）",
    	accountingInfo2: "财务支付（记账日／凭证抬头文本）",
    	accountingDate:"记账日",
    	voucherHeader:"凭证抬头文本",
    	debtorFlag:"借贷区分",
    	expBroadCory:"经费项目",
    	vaAccountingSubject:"科目",
    	paymentAmountTaxIn:"含税金额",
    	taxRate:"税率",
    	paymentAmountTaxOut:"费用金额",
    	taxAmount:"税额",
    	currency:"币种",
    	origExchangeRate:"汇率",
    	costCenterCd:"成本中心",
    	vaInvoice:"发票",
    	vaPartnerCd:"合作伙伴",
    	summary:"行文本摘要"
    	},
    'ja':{
    	expSubCategategory:"経費大分類",
    	expSubCategory:"経費小分類",
    	commonMsg:"基本情報",
    	applyDate:"申請日",
    	hopePayDate:"希望支払日",
    	companyCd:"会社名称",
    	instruction:"説明",
    	payAmount:"金額",
    	payMethod:"支払方式",
    	accountingInfo1: "財務支払（転記日／希望支払日／仕訳概要テキスト）",
    	accountingInfo2: "財務支払（転記日／仕訳概要テキスト）",
    	accountingDate:"転記日",
    	voucherHeader:"仕訳概要テキスト",
    	debtorFlag:"借貸区分",
    	expBroadCory:"経費項目",
    	vaAccountingSubject:"勘定科目",
    	paymentAmountTaxIn:"税込金額",
    	taxRate:"税率",
    	paymentAmountTaxOut:"費用金額<br />&nbsp;&nbsp;(CNY)",
    	taxAmount:"税額",
    	currency:"通貨",
    	origExchangeRate:"為替レート",
    	costCenterCd:"コストセンター",
    	vaInvoice:"発票",
    	vaPartnerCd:"パートナー",
    	summary:"仕訳明細テキスト"
    	},
    'en':{
    	expSubCategategory:"Large Expense Type",
    	expSubCategory:"Small Expense Type",
    	commonMsg:"Basic Information",
    	applyDate:"Apply Date",
    	hopePayDate:"Hope to pay day",
    	companyCd:"Company Name",
    	instruction:"Description",
    	payAmount:"Amount",
    	payMethod:"Payment Way",
    	accountingInfo1: "Payment（Posting Date／Hope to pay day／Journal Outline Text）",
    	accountingInfo2: "Payment（Posting Date／Journal Outline Text）",
    	accountingDate:"Billing date",
    	voucherHeader:"Journal Outline Text",
    	debtorFlag:"Debit/Credit",
    	expBroadCory:"Expense Items",
    	vaAccountingSubject:"Accounting Items",
    	paymentAmountTaxIn:"Including Tax Amount",
    	taxRate:"Tax Rate",
    	paymentAmountTaxOut:"Excluding Tax Amount(CNY)",
    	taxAmount:"Tax Amount",
    	currency:"Currency",
    	origExchangeRate:"Exchange Rate",
    	costCenterCd:"Cost Centre",
    	vaInvoice:"Invoice",
    	vaPartnerCd:"Partner",
    	summary:"Journal Detail Text"
    }
});