definer('i18n.wx.common.workflow.process.approve', {
    'zh_CN': {
    	authUser: "处理者",
    	authDepartment: "负责部门",
    	stampInfo: "电子印章",
    	comment: "注解",
    	btnApprove: "审批",
    	btnBack: "返回",
    	matterNumber: "案件号",
    	matterName: "案件名",
    	applayInfo: "申请信息",
    	applyUserName: "申请人",
    	applyBaseDate: "申请基准日",
    	applyDate: "申请日",
    	matterProcessing: "案件处理中...",
    	financialErrMsg: "财务支付信息不能为空，请在PC端进行审批",
    	dataCommiting: "处理中...",
    	stampMsg: "请设置印章。"
    },
    'ja': {
    	authUser: "処理者",
    	authDepartment: "担当組織",
    	stampInfo: "印影",
    	comment: "コメント",
    	btnApprove: "承認",
    	btnBack: "戻る",
    	matterNumber: "案件番号",
    	matterName: "案件名",
    	applayInfo: "申請情報",
    	applyUserName: "申請者",
    	applyBaseDate: "申請基準日",
    	applyDate: "申請日",
    	matterProcessing: "案件処理中...",
        financialErrMsg: "財務支払情報の入力は必須です。PCで承認してください。",
        dataCommiting: "処理中...",
        stampMsg: "印鑑を追加してください。"
    },
    'en': {
    	authUser: "Handler",
    	authDepartment: "Responsible Dept",
    	stampInfo: "Seal",
    	comment: "Comment",
    	btnApprove: "Approve",
    	btnBack: "Return",
    	matterNumber: "Application No.",
    	matterName: "Application Name",
    	applayInfo: "Application Information",
    	applyUserName: "Applicant",
    	applyBaseDate: "Application Base Date",
    	applyDate: "Apply Date",
    	matterProcessing: "The matter is in processing...",
        financialErrMsg: "财务支付信息不能为空，请在PC端进行审批",
        dataCommiting: "processing...",
        stampMsg: "印鑑を追加してください。"
    }
});