definer('i18n.wx.ysw.yexp.exp0301.approveview', {
    'zh_CN': {
    	basicInfoTitle: "基本信息",
    	applyDate: "申请日",
    	projectCd: "项目代码",
    	projectName: "项目名",
    	pmName: "项目负责人",
    	bizTripDuration: "出差期间",
    	overseasFlagName: "国内国外区分",
    	bizTripPurpose: "出差的内容和目的",
    	companyName: "公司名称",
    	buName: "事业部",
    	deptName: "部门",
    	costCenterName: "成本中心",
    	borrowingAmountTitle: "借款金额",
    	borrowingAmount: "金额",
    	borrowingAmountCurrency: "币种",
    	borrowingAmountPayMathod: "支付方式",
    	borrowingAmountHopePayDate: "希望支付日",
    	bizTripSchedule: "出差日程",
    	bizTripDivName: "出差区分",
    	distanceTypeName: "距离",
    	schedulePlace: "出差地",
    	scheduleStartDate: "开始日",
    	scheduleEndDate: "结束日",
    	scheduleDays: "天数",
    	subsidiesDays: "补贴天数",
    	flightTicket: "公司代订",
    	flightTicketDepartDate: "日期",
    	flightTicketTransportTypeName: "交通工具",
    	flightTicketTicketNumber: "班次",
    	flightTicketTrafficStartTime: "出发时间",
    	flightTicketTrafficEndTime: "到达时间",
    	flightTicketTransportFrom: "出发地",
    	flightTicketTransportTo: "到达地",
    	flightTicketTicketQuantity: "数量",
    	flightTicketTicketPrice: "单价",
    	flightTicketTicketAmount: "预算金额",
    	flightTicketTicketCurrencyName: "币种",
    	railwayTicket: "个人预订",
    	railwayTicketDepartDate: "日期",
    	railwayTicketTransportTypeName: "交通工具",
    	railwayTicketTicketNumber: "班次",
    	railwayTicketTrafficStartTime: "出发时间",
    	railwayTicketTrafficEndTime: "到达时间",
    	railwayTicketTransportFrom: "出发地",
    	railwayTicketTransportTo: "到达地",
    	railwayTicketTicketQuantity: "数量",
    	railwayTicketTicketPrice: "单价",
    	railwayTicketTicketAmount: "预算金额",
    	railwayTicketTicketCurrencyName: "币种",
    	hotelRequired: "有住宿",
    	hotelDestinationDivName: "住宿地区分",
    	hotelName: "酒店名",
    	hotelStartDate: "开始日",
    	hotelEndDate: "结束日",
    	hotelDays: "天数",
    	hotelPrice: "单价",
    	hotelAmount: "总额",
    	hotelCurrencyName: "币种",
    	allowance: "补贴",
    	budgetSummary: "出差预算合计（个人／公司）",
    	ticketBudget: "交通费预算",
    	hotelBudget: "住宿预算",
    	allowanceBudget: "补贴",
    	budgetSubTotal: "小计",
    	budgetTotal: "预算总金额",
    	accountingInfo1: "财务支付（记账日／希望支付日／凭证抬头文本）",
    	accountingInfo2: "财务支付（记账日／凭证抬头文本）",
    	accountingDebtorFlagName: "借贷区分",
    	accountingExpBroadCategoryName: "经费大分类",
    	accountingExpSubCategoryName: "经费小分类",
    	accountingExpItemName: "经费项目",
    	accountingSubjectName: "科目",
    	accountingPaymentAmountTaxIn: "含税金额",
    	accountingTaxRate: "税率",
    	accountingPaymentAmountTaxOut: "费用金额",
    	accountingTaxAmount: "税额",
    	accountingCurrencyName: "币种",
    	accountingExchangeRate: "汇率",
    	accountingCostCenterCd: "成本中心",
    	accountingInvoice: "发票",
    	accountingPartner: "合作伙伴",
    	accountingSummary: "行文本摘要",
    	dayAllowance: "日补贴："
    },
    'ja': {
    	basicInfoTitle: "基本情報",
    	applyDate: "申請日",
    	projectCd: "プロジェクトコード",
    	projectName: "プロジェクト名称",
    	pmName: "プロジェクト責任者",
    	bizTripDuration: "出張期間",
    	overseasFlagName: "国内海外区分",
    	bizTripPurpose: "出張内容と目的",
    	companyName: "会社名称",
    	buName: "事業部",
    	deptName: "部門",
    	costCenterName: "コストセンター",
    	borrowingAmountTitle: "仮払金額",
    	borrowingAmount: "金額",
    	borrowingAmountCurrency: "通貨",
    	borrowingAmountPayMathod: "支払方式",
    	borrowingAmountHopePayDate: "希望支払日",
    	bizTripSchedule: "出張日程",
    	bizTripDivName: "出張区分",
    	distanceTypeName: "距離",
    	schedulePlace: "出張先",
    	scheduleStartDate: "開始日",
    	scheduleEndDate: "終了日",
    	scheduleDays: "日数",
    	subsidiesDays: "手当日数",
    	flightTicket: "会社予約",
    	flightTicketDepartDate: "日付",
    	flightTicketTransportTypeName: "交通機関",
    	flightTicketTicketNumber: "便名",
    	flightTicketTrafficStartTime: "出発時間",
    	flightTicketTrafficEndTime: "到着時間",
    	flightTicketTransportFrom: "出発地",
    	flightTicketTransportTo: "到着地",
    	flightTicketTicketQuantity: "個数",
    	flightTicketTicketPrice: "単価",
    	flightTicketTicketAmount: "予算金額",
    	flightTicketTicketCurrencyName: "通貨",
    	railwayTicket: "個人予定",
    	railwayTicketDepartDate: "日付",
    	railwayTicketTransportTypeName: "交通機関",
    	railwayTicketTicketNumber: "便名",
    	railwayTicketTrafficStartTime: "出発時間",
    	railwayTicketTrafficEndTime: "到着時間",
    	railwayTicketTransportFrom: "出発地",
    	railwayTicketTransportTo: "到着地",
    	railwayTicketTicketQuantity: "個数",
    	railwayTicketTicketPrice: "単価",
    	railwayTicketTicketAmount: "予算金額",
    	railwayTicketTicketCurrencyName: "通貨",
    	hotelRequired: "宿泊あり",
    	hotelDestinationDivName: "宿泊地区分",
    	hotelName: "ホテル名",
    	hotelStartDate: "開始日",
    	hotelEndDate: "終了日",
    	hotelDays: "日数",
    	hotelPrice: "単価",
    	hotelAmount: "総額",
    	hotelCurrencyName: "通貨",
    	allowance: "手当",
    	budgetSummary: "出張予算合計（個人／会社）",
    	ticketBudget: "交通費予算",
    	hotelBudget: "宿泊予算",
    	allowanceBudget: "手当",
    	budgetSubTotal: "合計",
    	budgetTotal: "予算総額",
    	accountingInfo1: "財務支払（転記日／希望支払日／仕訳概要テキスト）",
    	accountingInfo2: "財務支払（転記日／仕訳概要テキスト）",
    	accountingDebtorFlagName: "借貸区分",
    	accountingExpBroadCategoryName: "経費大分類",
    	accountingExpSubCategoryName: "経費小分類",
    	accountingExpItemName: "経費項目",
    	accountingSubjectName: "勘定科目",
    	accountingPaymentAmountTaxIn: "税込総額",
    	accountingTaxRate: "税率",
    	accountingPaymentAmountTaxOut: "費用金額",
    	accountingTaxAmount: "税額",
    	accountingCurrencyName: "通貨",
    	accountingExchangeRate: "為替レート",
    	accountingCostCenterCd: "コストセンター",
    	accountingInvoice: "発票",
    	accountingPartner: "パートナー",
    	accountingSummary: "仕訳明細テキスト",
    	dayAllowance: "日当："
    },
    'en': {
    	basicInfoTitle: "Basic Information",
    	applyDate: "Apply Date",
    	projectCd: "PJ Cd",
    	projectName: "PJ Name",
    	pmName: "PM",
    	bizTripDuration: "Business Trip Duration",
    	overseasFlagName: "Domestic/Abroad",
    	bizTripPurpose: "Purpose",
    	companyName: "Company Name",
    	buName: "Business Department",
    	deptName: "Department",
    	costCenterName: "Cost Centre",
    	borrowingAmountTitle: "Loan Offset Amount",
    	borrowingAmount: "Amount",
    	borrowingAmountCurrency: "Currency",
    	borrowingAmountPayMathod: "Payment Way",
    	borrowingAmountHopePayDate: "Hope to pay day",
    	bizTripSchedule: "Schedule",
    	bizTripDivName: "Business Trip Type",
    	distanceTypeName: "Distance",
    	schedulePlace: "Destination",
    	scheduleStartDate: "Start Date",
    	scheduleEndDate: "End Date",
    	scheduleDays: "Days",
    	subsidiesDays: "Subsidy days",
    	flightTicket: "Company Booking",
    	flightTicketDepartDate: "Date",
    	flightTicketTransportTypeName: "Transportation",
    	flightTicketTicketNumber: "Shifts",
    	flightTicketTrafficStartTime: "Departure Time",
    	flightTicketTrafficEndTime: "Arrive Time",
    	flightTicketTransportFrom: "Departure",
    	flightTicketTransportTo: "Arrive",
    	flightTicketTicketQuantity: "Number",
    	flightTicketTicketPrice: "Unit-price",
    	flightTicketTicketAmount: "Budget",
    	flightTicketTicketCurrencyName: "Currency",
    	railwayTicket: "Personal reservation",
    	railwayTicketDepartDate: "Date",
    	railwayTicketTransportTypeName: "Transportation",
    	railwayTicketTicketNumber: "Shifts",
    	railwayTicketTrafficStartTime: "Departure Time",
    	railwayTicketTrafficEndTime: "Arrive Time",
    	railwayTicketTransportFrom: "Departure",
    	railwayTicketTransportTo: "Arrive",
    	railwayTicketTicketQuantity: "Number",
    	railwayTicketTicketPrice: "Unit-price",
    	railwayTicketTicketAmount: "Budget",
    	railwayTicketTicketCurrencyName: "Currency",
    	hotelRequired: "Hotel",
    	hotelDestinationDivName: "Accommodation area",
    	hotelName: "Hotel Name",
    	hotelStartDate: "Start Date",
    	hotelEndDate: "End Date",
    	hotelDays: "Days",
    	hotelPrice: "Unit-price",
    	hotelAmount: "Total Amount",
    	hotelCurrencyName: "Currency",
    	allowance: "Allowance",
    	budgetSummary: "Total Business Trip Budget Amount（Personal／Company）",
    	ticketBudget: "Travel budget",
    	hotelBudget: "Accommodation Budget",
    	allowanceBudget: "Allowance",
    	budgetSubTotal: "Total Amount",
    	budgetTotal: "Total budget",
    	accountingInfo1: "Payment（Posting Date／Hope to pay day／Journal Outline Text）",
    	accountingInfo2: "Payment（Posting Date／Journal Outline Text）",
    	accountingDebtorFlagName: "Debit/Credit",
    	accountingExpBroadCategoryName: "Large Expense Type",
    	accountingExpSubCategoryName: "Small Expense Type",
    	accountingExpItemName: "Expense Items",
    	accountingSubjectName: "Accounting Items",
    	accountingPaymentAmountTaxIn: "Including Tax Amount",
    	accountingTaxRate: "Tax Rate",
    	accountingPaymentAmountTaxOut: "Excluding Tax Amount(CNY)",
    	accountingTaxAmount: "Tax Amount",
    	accountingCurrencyName: "Currency",
    	accountingExchangeRate: "Exchange Rate",
    	accountingCostCenterCd: "Cost Centre",
    	accountingInvoice: "Invoice",
    	accountingPartner: "Partner",
    	accountingSummary: "Journal Detail Text",
    	dayAllowance: "Allowance："
    }
});
