package com.xiaoniu.walking.web.core.model.ext;

import com.xiaoniu.architecture.page.api.bean.DefaultPageParameter;
import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
@Data
public class MarketCostExt extends DefaultPageParameter implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cost.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cost.cast_date
     *
     * @mbggenerated
     */
    private Date castDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cost.channel
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cost.principal
     *
     * @mbggenerated
     */
    private String principal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cost.account_consume
     *
     * @mbggenerated
     */
    private BigDecimal accountConsume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cost.ad_click_num
     *
     * @mbggenerated
     */
    private Integer adClickNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cost.install_num
     *
     * @mbggenerated
     */
    private Integer installNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cost.anti_point
     *
     * @mbggenerated
     */
    private String antiPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cost.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cost.create_man
     *
     * @mbggenerated
     */
    private String createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cost.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cost.modify_man
     *
     * @mbggenerated
     */
    private String modifyMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cost.remark
     *
     * @mbggenerated
     */
    private String remark;


}